version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditdb
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6

  backend:
    build: ./backend
    depends_on: [db, redis, ai-service]
    env_file: ['./backend/.env']
    ports:
      - '8000:8000'

  ai-service:
    build: ./ai-service
    ports:
      - '8001:8001'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

volumes:
  db-data: